### ISSUE TITLE
Invalid Plugin: miss main.js

### ISSUE THREAD

**Issue by sjhsbhqf** [syaoranwe/pot-app-translate-plugin-baidu-ernie-free#1]
关于x86_64-pc-windows-msvc.zip

1、首先是报错文件名开始不是plugin，然后我把[plugin]改成了plugin

![image](https://github.com/user-attachments/assets/2192f080-3cd6-4685-908f-f214a6d1d98e)

2、其次会报错【Invalid Plugin: miss main.js】

![image](https://github.com/user-attachments/assets/0b1846b0-e989-4c6d-b103-fa6bbec5ed9a)

**Comment by syaoranwe** [comment]
需要使用最新的pot app和打包的最新版本插件。新旧程序和插件不兼容。
